version: "3"

services:
  app:
    container_name: 'docker-mongo-and-node'
    build: .
    ports:
      - "8080:3000"
    links:
      - mongo
    restart: 'always'
  
  mongo:
    container_name: 'mongo'
    image: mongo
    ports:
      - "27017:27017"
